import React from "react";

const page = () => {
  return (
    <div className="px-5 md:px-12 lg:px-24 py-10 md:py-14 lg:py-16 bg-white text-[#6E2F2F]">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl md:text-4xl font-semibold">
          TERMS AND CONDITIONS OF MEMBERSHIP
        </h1>
        <h2 className="mt-2 text-2xl font-semibold">RVR LUXURY MATRIMONY</h2>
        <p className="mt-6 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          Welcome to RVR Luxury Matrimony (herein referred to as &quot;RVR&quot;).
        </p>

        <p className="mt-4 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and rules thereunder. This electronic record is
          generated by a computer system and does not require any physical or
          digital signatures. This document is published in accordance with the
          provisions of Rule 3 (1) of the Information Technology (Intermediaries
          Guidelines and Digital Media Ethics Code) Rules, 2021.
        </p>

        <p className="mt-4 text-base md:text-lg leading-7 text-[#6E2F2F]/90 font-semibold">
          PLEASE READ THESE TERMS CAREFULLY. Accessing, browsing, or otherwise
          using the Website/App implies your agreement to be bound by all these
          Terms and Conditions (&quot;Agreement&quot;). In these Terms, &quot;RVR
          Member&quot; refers to the end user (including parents or relatives
          registering on behalf of a bride/groom).
        </p>

        <h2 className="mt-10 text-2xl font-semibold">1. Eligibility</h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> Membership is reserved for
            Indian Nationals, PIOs, NRIs, and Persons of Indian Descent.
          </li>
          <li>
            <span className="font-semibold">B)</span> You confirm you are 18+
            (Women) or 21+ (Men). If awaiting divorce, you must select
            &quot;Awaiting Divorce.&quot;
          </li>
          <li>
            <span className="font-semibold">C)</span> Registrants creating
            profiles for others confirm they have obtained explicit consent from
            the profile subject.
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">
          2. Registration &amp; Account Security
        </h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> You agree to furnish true,
            accurate, and complete information, including recent photos (not
            older than 3 months). RVR may reproduce profile info across its
            community-specific sub-domains for better matching.
          </li>
          <li>
            <span className="font-semibold">B)</span> Untrue or incomplete info
            gives RVR the right to terminate membership and forfeit paid fees
            without notice.
          </li>
          <li>
            <span className="font-semibold">C)</span> Duplicate profiles are not
            allowed and will be deleted.
          </li>
          <li>
            <span className="font-semibold">D)</span> You are responsible for
            safeguarding login credentials (ID, Password, OTP). RVR will never
            ask for your password.
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">
          3. Role and Responsibility of RVR
        </h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> RVR provides an
            &quot;as-is&quot; platform for users to search prospects independently.
          </li>
          <li>
            <span className="font-semibold">B)</span> Matches are system-generated
            based on your &quot;Partner Preferences.&quot; Changes to preferences
            will update automated results.
          </li>
          <li>
            <span className="font-semibold">C)</span> Secure Connect: We provide a
            safety feature for women to receive calls from premium members without
            revealing their mobile numbers.
          </li>
          <li>
            <span className="font-semibold">D)</span> RVR does not authenticate
            profile info; users must verify credentials independently.
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">
          4. Role and Responsibility of RVR Member
        </h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> Members must verify marital
            status, education, occupation, and health status of prospects before
            finalizing alliances.
          </li>
          <li>
            <span className="font-semibold">B)</span> Health Records: Members are
            expected to disclose pre-existing illnesses or disabilities during
            enrollment.
          </li>
          <li>
            <span className="font-semibold">C)</span> Financial Safety: Do NOT
            enter into financial transactions with prospects. Report any user
            asking for money immediately.
          </li>
          <li>
            <span className="font-semibold">D)</span> No Bots/Scripts: Use of
            automated programs to communicate or scrape data is strictly
            prohibited.
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">
          5. Communication and Confidentiality
        </h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> You consent to receive
            promotional and transactional communications via Email, SMS, Call, or
            WhatsApp, even if registered on DND/NCPR.
          </li>
          <li>
            <span className="font-semibold">B)</span> Feedback provided to RVR is
            deemed non-confidential and can be used by RVR without compensation.
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">6. Grievance Cell</h2>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          In case of violations (obscenity, impersonation, etc.), contact:
        </p>
        <div className="mt-4 text-base md:text-lg leading-7 text-[#6E2F2F]/90 space-y-1">
          {/* <p>
            <span className="font-semibold">Grievance Officer:</span> [Insert
            Name]
          </p> */}
          <p>
            <span className="font-semibold">Address:</span> Brindavanam Street,
            Near Muthoot Finance Office, Trunk Road, Kavali - 524201.
          </p>
          <p>
            <span className="font-semibold">Email:</span> rvrluxurymatrimony@gmail.com
          </p>
          <p>
            <span className="font-semibold">Hours:</span> 10 AM – 6 PM IST
            (Mon–Sat).
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold">7. Limitation of Liability</h2>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          RVR is not liable for direct or indirect damages resulting from the use
          of the site or interactions between members. Our liability is limited to
          the specific amount paid for your current membership package.
        </p>

        <h2 className="mt-10 text-2xl font-semibold">8. Moneyback Guarantee</h2>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          Get a full refund if no match is found within 21 days, provided:
        </p>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>Minimum 3 photos added.</li>
          <li>Profile is Govt ID verified.</li>
          <li>Completion score is 80%+.</li>
          <li>Messaged at least 15 mutual matches with zero replies.</li>
          <li>No phone numbers have been &quot;viewed/consumed&quot; from the package.</li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">
          9. Membership Packages &amp; Fair Usage Policy (FUP)
        </h2>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          We offer Gold, Diamond, Platinum, and Assisted packages.
        </p>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          FUP Limits: To prevent database abuse, daily/weekly limits apply to
          &quot;Phone View&quot; and &quot;Personal Messages.&quot;
        </p>
        <div className="mt-4 text-base md:text-lg leading-7 text-[#6E2F2F]/90 space-y-1">
          <p>
            <span className="font-semibold">Standard Limits:</span> * Daily: 100
            Messages / 30 Phone Views.
          </p>
          <p>Monthly: 500 Messages / 100 Phone Views.</p>
          <p>One month is computed as 30 days.</p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold">
          10. Doorstep Services (Kavali Region)
        </h2>
        <div className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90 space-y-1">
          <p>
            <span className="font-semibold">Service:</span> A representative can
            visit your home (within Kavali territory) to assist in profile
            creation and package selection.
          </p>
          <p>
            <span className="font-semibold">Fee:</span> A non-refundable visit
            fee of Rs. 99/- applies.
          </p>
          <p>
            <span className="font-semibold">Safety:</span> Members must treat
            agents with respect. Financial transactions directly with agents are
            prohibited.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold">
          11. Standard against Child Sexual Exploitation
        </h2>
        <ul className="mt-4 list-disc pl-5 space-y-2 text-base md:text-lg text-[#6E2F2F]/90">
          <li>
            <span className="font-semibold">A)</span> Use is strictly 18+. CSAM
            (Child Sexual Abuse Material) is prohibited.
          </li>
          <li>
            <span className="font-semibold">B)</span> We scan content for CSAM.
            Violations result in immediate permanent bans and reporting to
            [suspicious link removed].
          </li>
        </ul>

        <h2 className="mt-10 text-2xl font-semibold">12. Jurisdiction</h2>
        <p className="mt-3 text-base md:text-lg leading-7 text-[#6E2F2F]/90">
          This agreement is deemed entered into in Kavali, Andhra Pradesh.
          Disputes are governed by Indian Law and subject to the exclusive
          jurisdiction of courts in Kavali/Nellore.
        </p>
      </div>
    </div>
  );
};

export default page;
